const foods = [
  {
    itemid: '1',
    name: 'Veg Pizza',
    image: require('../assets/meatPizza.png'),
    ingrediants: 'For the veg lovers',
    qty: 1,
    price: '49',
    checked:1,
  },
  {
    itemid: '2',
    name: 'Margareita',
    ingrediants: 'Cheese Pizza',
    price: '79',
    image: require('../assets/cheesePizza.png'),
    qty:1,
    checked:1,
  },
  {
    itemid: '3',
    name: ' Veg Burger',
    ingrediants: 'Filled with Veggies',
    price: '49',
    image: require('../assets/chickenBurger.png'),
    qty:1,
    checked:1,
  },
  {
    itemid: '4',
    name: 'Misal',
    ingrediants: 'Misal Pav',
    price: '39',
    image: require('../assets/mp.jpg'),
    qty:1,
    checked:1,
  },
  {
    id: '5',
    name: 'Aloo Paratha',
    ingrediants: 'Parantha with Dahi',
    price: '20',
    image: require('../assets/aloo-paratha-recipe.jpg'),
    qty:1,
    checked:1,
  },
  {
    id: '6',
    name: 'Orange Juice',
    ingrediants: 'Refreshing',
    price: '15',
    image: require('../assets/mosambi.jpg'),
    qty:1,
    checked:1,
  },
  {
    id: '7',
    name: 'Samosa',
    ingrediants: 'Refreshing',
    price: '15',
    image: require('../assets/Samosa.jpg'),
    qty:1,
    checked:1,
  },
  {
    id: '8',
    name: 'Masala Dosa',
    ingrediants: 'Tasty and filling',
    price: '29',
    image: require('../assets/dosa1.jpg'),
    qty:1,
    checked:1,
  },
];

export default foods;
